// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compact_descriptor.proto

#ifndef PROTOBUF_compact_5fdescriptor_2eproto__INCLUDED
#define PROTOBUF_compact_5fdescriptor_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace compact_descriptor {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_compact_5fdescriptor_2eproto();
void protobuf_AssignDesc_compact_5fdescriptor_2eproto();
void protobuf_ShutdownFile_compact_5fdescriptor_2eproto();

class Description;
class Component;
class Attribute;

enum Component_Type {
  Component_Type_Rack = 0,
  Component_Type_Module = 1,
  Component_Type_Knob = 2,
  Component_Type_Selector = 3,
  Component_Type_ValueInputPort = 4,
  Component_Type_ValueOutputPort = 5,
  Component_Type_NoteInputPort = 6,
  Component_Type_NoteOutputPort = 7
};
bool Component_Type_IsValid(int value);
const Component_Type Component_Type_Type_MIN = Component_Type_Rack;
const Component_Type Component_Type_Type_MAX = Component_Type_NoteOutputPort;
const int Component_Type_Type_ARRAYSIZE = Component_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Component_Type_descriptor();
inline const ::std::string& Component_Type_Name(Component_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Component_Type_descriptor(), value);
}
inline bool Component_Type_Parse(
    const ::std::string& name, Component_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Component_Type>(
    Component_Type_descriptor(), name, value);
}
enum Attribute_Type {
  Attribute_Type_Value = 0,
  Attribute_Type_Scale = 1,
  Attribute_Type_Choices = 2,
  Attribute_Type_WireId = 3,
  Attribute_Type_Direction = 4,
  Attribute_Type_Signal = 5,
  Attribute_Type_ModuleType = 6,
  Attribute_Type_SelectorIndex = 7
};
bool Attribute_Type_IsValid(int value);
const Attribute_Type Attribute_Type_Type_MIN = Attribute_Type_Value;
const Attribute_Type Attribute_Type_Type_MAX = Attribute_Type_SelectorIndex;
const int Attribute_Type_Type_ARRAYSIZE = Attribute_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Attribute_Type_descriptor();
inline const ::std::string& Attribute_Type_Name(Attribute_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Attribute_Type_descriptor(), value);
}
inline bool Attribute_Type_Parse(
    const ::std::string& name, Attribute_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Attribute_Type>(
    Attribute_Type_descriptor(), name, value);
}
// ===================================================================

class Description : public ::google::protobuf::Message {
 public:
  Description();
  virtual ~Description();

  Description(const Description& from);

  inline Description& operator=(const Description& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Description& default_instance();

  void Swap(Description* other);

  // implements Message ----------------------------------------------

  Description* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Description& from);
  void MergeFrom(const Description& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .compact_descriptor.Component component = 1;
  inline int component_size() const;
  inline void clear_component();
  static const int kComponentFieldNumber = 1;
  inline const ::compact_descriptor::Component& component(int index) const;
  inline ::compact_descriptor::Component* mutable_component(int index);
  inline ::compact_descriptor::Component* add_component();
  inline const ::google::protobuf::RepeatedPtrField< ::compact_descriptor::Component >&
      component() const;
  inline ::google::protobuf::RepeatedPtrField< ::compact_descriptor::Component >*
      mutable_component();

  // @@protoc_insertion_point(class_scope:compact_descriptor.Description)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::compact_descriptor::Component > component_;
  friend void  protobuf_AddDesc_compact_5fdescriptor_2eproto();
  friend void protobuf_AssignDesc_compact_5fdescriptor_2eproto();
  friend void protobuf_ShutdownFile_compact_5fdescriptor_2eproto();

  void InitAsDefaultInstance();
  static Description* default_instance_;
};
// -------------------------------------------------------------------

class Component : public ::google::protobuf::Message {
 public:
  Component();
  virtual ~Component();

  Component(const Component& from);

  inline Component& operator=(const Component& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Component& default_instance();

  void Swap(Component* other);

  // implements Message ----------------------------------------------

  Component* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Component& from);
  void MergeFrom(const Component& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Component_Type Type;
  static const Type Rack = Component_Type_Rack;
  static const Type Module = Component_Type_Module;
  static const Type Knob = Component_Type_Knob;
  static const Type Selector = Component_Type_Selector;
  static const Type ValueInputPort = Component_Type_ValueInputPort;
  static const Type ValueOutputPort = Component_Type_ValueOutputPort;
  static const Type NoteInputPort = Component_Type_NoteInputPort;
  static const Type NoteOutputPort = Component_Type_NoteOutputPort;
  static inline bool Type_IsValid(int value) {
    return Component_Type_IsValid(value);
  }
  static const Type Type_MIN =
    Component_Type_Type_MIN;
  static const Type Type_MAX =
    Component_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    Component_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return Component_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return Component_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return Component_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required .compact_descriptor.Component.Type type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::compact_descriptor::Component_Type type() const;
  inline void set_type(::compact_descriptor::Component_Type value);

  // optional uint32 id = 3;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 3;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // repeated .compact_descriptor.Attribute attribute = 4;
  inline int attribute_size() const;
  inline void clear_attribute();
  static const int kAttributeFieldNumber = 4;
  inline const ::compact_descriptor::Attribute& attribute(int index) const;
  inline ::compact_descriptor::Attribute* mutable_attribute(int index);
  inline ::compact_descriptor::Attribute* add_attribute();
  inline const ::google::protobuf::RepeatedPtrField< ::compact_descriptor::Attribute >&
      attribute() const;
  inline ::google::protobuf::RepeatedPtrField< ::compact_descriptor::Attribute >*
      mutable_attribute();

  // repeated .compact_descriptor.Component sub_component = 5;
  inline int sub_component_size() const;
  inline void clear_sub_component();
  static const int kSubComponentFieldNumber = 5;
  inline const ::compact_descriptor::Component& sub_component(int index) const;
  inline ::compact_descriptor::Component* mutable_sub_component(int index);
  inline ::compact_descriptor::Component* add_sub_component();
  inline const ::google::protobuf::RepeatedPtrField< ::compact_descriptor::Component >&
      sub_component() const;
  inline ::google::protobuf::RepeatedPtrField< ::compact_descriptor::Component >*
      mutable_sub_component();

  // @@protoc_insertion_point(class_scope:compact_descriptor.Component)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  int type_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::RepeatedPtrField< ::compact_descriptor::Attribute > attribute_;
  ::google::protobuf::RepeatedPtrField< ::compact_descriptor::Component > sub_component_;
  friend void  protobuf_AddDesc_compact_5fdescriptor_2eproto();
  friend void protobuf_AssignDesc_compact_5fdescriptor_2eproto();
  friend void protobuf_ShutdownFile_compact_5fdescriptor_2eproto();

  void InitAsDefaultInstance();
  static Component* default_instance_;
};
// -------------------------------------------------------------------

class Attribute : public ::google::protobuf::Message {
 public:
  Attribute();
  virtual ~Attribute();

  Attribute(const Attribute& from);

  inline Attribute& operator=(const Attribute& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Attribute& default_instance();

  void Swap(Attribute* other);

  // implements Message ----------------------------------------------

  Attribute* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Attribute& from);
  void MergeFrom(const Attribute& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Attribute_Type Type;
  static const Type Value = Attribute_Type_Value;
  static const Type Scale = Attribute_Type_Scale;
  static const Type Choices = Attribute_Type_Choices;
  static const Type WireId = Attribute_Type_WireId;
  static const Type Direction = Attribute_Type_Direction;
  static const Type Signal = Attribute_Type_Signal;
  static const Type ModuleType = Attribute_Type_ModuleType;
  static const Type SelectorIndex = Attribute_Type_SelectorIndex;
  static inline bool Type_IsValid(int value) {
    return Attribute_Type_IsValid(value);
  }
  static const Type Type_MIN =
    Attribute_Type_Type_MIN;
  static const Type Type_MAX =
    Attribute_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    Attribute_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return Attribute_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return Attribute_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return Attribute_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .compact_descriptor.Attribute.Type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::compact_descriptor::Attribute_Type type() const;
  inline void set_type(::compact_descriptor::Attribute_Type value);

  // optional uint32 ivalue = 2;
  inline bool has_ivalue() const;
  inline void clear_ivalue();
  static const int kIvalueFieldNumber = 2;
  inline ::google::protobuf::uint32 ivalue() const;
  inline void set_ivalue(::google::protobuf::uint32 value);

  // repeated string svalue = 3;
  inline int svalue_size() const;
  inline void clear_svalue();
  static const int kSvalueFieldNumber = 3;
  inline const ::std::string& svalue(int index) const;
  inline ::std::string* mutable_svalue(int index);
  inline void set_svalue(int index, const ::std::string& value);
  inline void set_svalue(int index, const char* value);
  inline void set_svalue(int index, const char* value, size_t size);
  inline ::std::string* add_svalue();
  inline void add_svalue(const ::std::string& value);
  inline void add_svalue(const char* value);
  inline void add_svalue(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& svalue() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_svalue();

  // optional uint32 id = 4;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 4;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:compact_descriptor.Attribute)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_ivalue();
  inline void clear_has_ivalue();
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int type_;
  ::google::protobuf::uint32 ivalue_;
  ::google::protobuf::RepeatedPtrField< ::std::string> svalue_;
  ::google::protobuf::uint32 id_;
  friend void  protobuf_AddDesc_compact_5fdescriptor_2eproto();
  friend void protobuf_AssignDesc_compact_5fdescriptor_2eproto();
  friend void protobuf_ShutdownFile_compact_5fdescriptor_2eproto();

  void InitAsDefaultInstance();
  static Attribute* default_instance_;
};
// ===================================================================


// ===================================================================

// Description

// repeated .compact_descriptor.Component component = 1;
inline int Description::component_size() const {
  return component_.size();
}
inline void Description::clear_component() {
  component_.Clear();
}
inline const ::compact_descriptor::Component& Description::component(int index) const {
  // @@protoc_insertion_point(field_get:compact_descriptor.Description.component)
  return component_.Get(index);
}
inline ::compact_descriptor::Component* Description::mutable_component(int index) {
  // @@protoc_insertion_point(field_mutable:compact_descriptor.Description.component)
  return component_.Mutable(index);
}
inline ::compact_descriptor::Component* Description::add_component() {
  // @@protoc_insertion_point(field_add:compact_descriptor.Description.component)
  return component_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::compact_descriptor::Component >&
Description::component() const {
  // @@protoc_insertion_point(field_list:compact_descriptor.Description.component)
  return component_;
}
inline ::google::protobuf::RepeatedPtrField< ::compact_descriptor::Component >*
Description::mutable_component() {
  // @@protoc_insertion_point(field_mutable_list:compact_descriptor.Description.component)
  return &component_;
}

// -------------------------------------------------------------------

// Component

// required string name = 1;
inline bool Component::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Component::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Component::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Component::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Component::name() const {
  // @@protoc_insertion_point(field_get:compact_descriptor.Component.name)
  return *name_;
}
inline void Component::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:compact_descriptor.Component.name)
}
inline void Component::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:compact_descriptor.Component.name)
}
inline void Component::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:compact_descriptor.Component.name)
}
inline ::std::string* Component::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:compact_descriptor.Component.name)
  return name_;
}
inline ::std::string* Component::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Component::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:compact_descriptor.Component.name)
}

// required .compact_descriptor.Component.Type type = 2;
inline bool Component::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Component::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Component::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Component::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::compact_descriptor::Component_Type Component::type() const {
  // @@protoc_insertion_point(field_get:compact_descriptor.Component.type)
  return static_cast< ::compact_descriptor::Component_Type >(type_);
}
inline void Component::set_type(::compact_descriptor::Component_Type value) {
  assert(::compact_descriptor::Component_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:compact_descriptor.Component.type)
}

// optional uint32 id = 3;
inline bool Component::has_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Component::set_has_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Component::clear_has_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Component::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 Component::id() const {
  // @@protoc_insertion_point(field_get:compact_descriptor.Component.id)
  return id_;
}
inline void Component::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:compact_descriptor.Component.id)
}

// repeated .compact_descriptor.Attribute attribute = 4;
inline int Component::attribute_size() const {
  return attribute_.size();
}
inline void Component::clear_attribute() {
  attribute_.Clear();
}
inline const ::compact_descriptor::Attribute& Component::attribute(int index) const {
  // @@protoc_insertion_point(field_get:compact_descriptor.Component.attribute)
  return attribute_.Get(index);
}
inline ::compact_descriptor::Attribute* Component::mutable_attribute(int index) {
  // @@protoc_insertion_point(field_mutable:compact_descriptor.Component.attribute)
  return attribute_.Mutable(index);
}
inline ::compact_descriptor::Attribute* Component::add_attribute() {
  // @@protoc_insertion_point(field_add:compact_descriptor.Component.attribute)
  return attribute_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::compact_descriptor::Attribute >&
Component::attribute() const {
  // @@protoc_insertion_point(field_list:compact_descriptor.Component.attribute)
  return attribute_;
}
inline ::google::protobuf::RepeatedPtrField< ::compact_descriptor::Attribute >*
Component::mutable_attribute() {
  // @@protoc_insertion_point(field_mutable_list:compact_descriptor.Component.attribute)
  return &attribute_;
}

// repeated .compact_descriptor.Component sub_component = 5;
inline int Component::sub_component_size() const {
  return sub_component_.size();
}
inline void Component::clear_sub_component() {
  sub_component_.Clear();
}
inline const ::compact_descriptor::Component& Component::sub_component(int index) const {
  // @@protoc_insertion_point(field_get:compact_descriptor.Component.sub_component)
  return sub_component_.Get(index);
}
inline ::compact_descriptor::Component* Component::mutable_sub_component(int index) {
  // @@protoc_insertion_point(field_mutable:compact_descriptor.Component.sub_component)
  return sub_component_.Mutable(index);
}
inline ::compact_descriptor::Component* Component::add_sub_component() {
  // @@protoc_insertion_point(field_add:compact_descriptor.Component.sub_component)
  return sub_component_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::compact_descriptor::Component >&
Component::sub_component() const {
  // @@protoc_insertion_point(field_list:compact_descriptor.Component.sub_component)
  return sub_component_;
}
inline ::google::protobuf::RepeatedPtrField< ::compact_descriptor::Component >*
Component::mutable_sub_component() {
  // @@protoc_insertion_point(field_mutable_list:compact_descriptor.Component.sub_component)
  return &sub_component_;
}

// -------------------------------------------------------------------

// Attribute

// required .compact_descriptor.Attribute.Type type = 1;
inline bool Attribute::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Attribute::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Attribute::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Attribute::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::compact_descriptor::Attribute_Type Attribute::type() const {
  // @@protoc_insertion_point(field_get:compact_descriptor.Attribute.type)
  return static_cast< ::compact_descriptor::Attribute_Type >(type_);
}
inline void Attribute::set_type(::compact_descriptor::Attribute_Type value) {
  assert(::compact_descriptor::Attribute_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:compact_descriptor.Attribute.type)
}

// optional uint32 ivalue = 2;
inline bool Attribute::has_ivalue() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Attribute::set_has_ivalue() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Attribute::clear_has_ivalue() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Attribute::clear_ivalue() {
  ivalue_ = 0u;
  clear_has_ivalue();
}
inline ::google::protobuf::uint32 Attribute::ivalue() const {
  // @@protoc_insertion_point(field_get:compact_descriptor.Attribute.ivalue)
  return ivalue_;
}
inline void Attribute::set_ivalue(::google::protobuf::uint32 value) {
  set_has_ivalue();
  ivalue_ = value;
  // @@protoc_insertion_point(field_set:compact_descriptor.Attribute.ivalue)
}

// repeated string svalue = 3;
inline int Attribute::svalue_size() const {
  return svalue_.size();
}
inline void Attribute::clear_svalue() {
  svalue_.Clear();
}
inline const ::std::string& Attribute::svalue(int index) const {
  // @@protoc_insertion_point(field_get:compact_descriptor.Attribute.svalue)
  return svalue_.Get(index);
}
inline ::std::string* Attribute::mutable_svalue(int index) {
  // @@protoc_insertion_point(field_mutable:compact_descriptor.Attribute.svalue)
  return svalue_.Mutable(index);
}
inline void Attribute::set_svalue(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:compact_descriptor.Attribute.svalue)
  svalue_.Mutable(index)->assign(value);
}
inline void Attribute::set_svalue(int index, const char* value) {
  svalue_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:compact_descriptor.Attribute.svalue)
}
inline void Attribute::set_svalue(int index, const char* value, size_t size) {
  svalue_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:compact_descriptor.Attribute.svalue)
}
inline ::std::string* Attribute::add_svalue() {
  return svalue_.Add();
}
inline void Attribute::add_svalue(const ::std::string& value) {
  svalue_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:compact_descriptor.Attribute.svalue)
}
inline void Attribute::add_svalue(const char* value) {
  svalue_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:compact_descriptor.Attribute.svalue)
}
inline void Attribute::add_svalue(const char* value, size_t size) {
  svalue_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:compact_descriptor.Attribute.svalue)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Attribute::svalue() const {
  // @@protoc_insertion_point(field_list:compact_descriptor.Attribute.svalue)
  return svalue_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Attribute::mutable_svalue() {
  // @@protoc_insertion_point(field_mutable_list:compact_descriptor.Attribute.svalue)
  return &svalue_;
}

// optional uint32 id = 4;
inline bool Attribute::has_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Attribute::set_has_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Attribute::clear_has_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Attribute::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 Attribute::id() const {
  // @@protoc_insertion_point(field_get:compact_descriptor.Attribute.id)
  return id_;
}
inline void Attribute::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:compact_descriptor.Attribute.id)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace compact_descriptor

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::compact_descriptor::Component_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::compact_descriptor::Component_Type>() {
  return ::compact_descriptor::Component_Type_descriptor();
}
template <> struct is_proto_enum< ::compact_descriptor::Attribute_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::compact_descriptor::Attribute_Type>() {
  return ::compact_descriptor::Attribute_Type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_compact_5fdescriptor_2eproto__INCLUDED
