# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import module_descriptor_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='connector.proto',
  package='connector',
  serialized_pb=_b('\n\x0f\x63onnector.proto\x12\tconnector\x1a\x17module_descriptor.proto\"\x92\x02\n\x07Request\x12+\n\x07\x63ommand\x18\x01 \x02(\x0e\x32\x1a.connector.Request.Command\x12\x0c\n\x04path\x18\x02 \x03(\t\x12\n\n\x02id\x18\x03 \x03(\r\x12\'\n\tattribute\x18\x04 \x01(\x0b\x32\x14.connector.Attribute\x12\'\n\tcomponent\x18\x05 \x01(\x0b\x32\x14.connector.Component\"n\n\x07\x43ommand\x12\x0c\n\x08\x44\x45SCRIBE\x10\x00\x12\x11\n\rSET_ATTRIBUTE\x10\x01\x12\x13\n\x0fUNSET_ATTRIBUTE\x10\x02\x12\x14\n\x10\x41\x44\x44_SUBCOMPONENT\x10\x03\x12\x17\n\x13REMOVE_SUBCOMPONENT\x10\x04\"\x8c\x01\n\x05Reply\x12\'\n\x06status\x18\x01 \x02(\x0e\x32\x17.connector.Reply.Status\x12\'\n\tcomponent\x18\x02 \x03(\x0b\x32\x14.connector.Component\x12\x0f\n\x07message\x18\x03 \x01(\t\" \n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x42\x1b\n\x19jp.gaje.analog3.connector')
  ,
  dependencies=[module_descriptor_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REQUEST_COMMAND = _descriptor.EnumDescriptor(
  name='Command',
  full_name='connector.Request.Command',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DESCRIBE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_ATTRIBUTE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSET_ATTRIBUTE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD_SUBCOMPONENT', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMOVE_SUBCOMPONENT', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=220,
  serialized_end=330,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_COMMAND)

_REPLY_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='connector.Reply.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=441,
  serialized_end=473,
)
_sym_db.RegisterEnumDescriptor(_REPLY_STATUS)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='connector.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='connector.Request.command', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='connector.Request.path', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='connector.Request.id', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='connector.Request.attribute', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='component', full_name='connector.Request.component', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_COMMAND,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=330,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='connector.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='connector.Reply.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='component', full_name='connector.Reply.component', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='connector.Reply.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REPLY_STATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=473,
)

_REQUEST.fields_by_name['command'].enum_type = _REQUEST_COMMAND
_REQUEST.fields_by_name['attribute'].message_type = module_descriptor_pb2._ATTRIBUTE
_REQUEST.fields_by_name['component'].message_type = module_descriptor_pb2._COMPONENT
_REQUEST_COMMAND.containing_type = _REQUEST
_REPLY.fields_by_name['status'].enum_type = _REPLY_STATUS
_REPLY.fields_by_name['component'].message_type = module_descriptor_pb2._COMPONENT
_REPLY_STATUS.containing_type = _REPLY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'connector_pb2'
  # @@protoc_insertion_point(class_scope:connector.Request)
  ))
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'connector_pb2'
  # @@protoc_insertion_point(class_scope:connector.Reply)
  ))
_sym_db.RegisterMessage(Reply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031jp.gaje.analog3.connector'))
# @@protoc_insertion_point(module_scope)
