# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: module_descriptor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='module_descriptor.proto',
  package='connector',
  serialized_pb=_b('\n\x17module_descriptor.proto\x12\tconnector\"6\n\x0b\x44\x65scription\x12\'\n\tcomponent\x18\x01 \x03(\x0b\x32\x14.connector.Component\"\xe4\x01\n\tComponent\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\'\n\x04type\x18\x02 \x01(\x0e\x32\x19.connector.Component.Type\x12\n\n\x02id\x18\x05 \x01(\r\x12\'\n\tattribute\x18\x03 \x03(\x0b\x32\x14.connector.Attribute\x12+\n\rsub_component\x18\x04 \x03(\x0b\x32\x14.connector.Component\">\n\x04Type\x12\x08\n\x04Rack\x10\x00\x12\n\n\x06Module\x10\x01\x12\x08\n\x04Knob\x10\x02\x12\x0c\n\x08Selector\x10\x03\x12\x08\n\x04Port\x10\x04\"F\n\tAttribute\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.connector.Value\x12\n\n\x02id\x18\x03 \x01(\r\"Y\n\x05Value\x12\x0e\n\x06svalue\x18\x01 \x01(\t\x12\x0e\n\x06ivalue\x18\x02 \x01(\x05\x12\x0e\n\x06\x64value\x18\x03 \x01(\x01\x12 \n\x06\x61value\x18\x04 \x03(\x0b\x32\x10.connector.ValueB\x1b\n\x19jp.gaje.analog3.connector')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_COMPONENT_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='connector.Component.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Rack', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Module', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Knob', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Selector', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Port', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=261,
  serialized_end=323,
)
_sym_db.RegisterEnumDescriptor(_COMPONENT_TYPE)


_DESCRIPTION = _descriptor.Descriptor(
  name='Description',
  full_name='connector.Description',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='component', full_name='connector.Description.component', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=92,
)


_COMPONENT = _descriptor.Descriptor(
  name='Component',
  full_name='connector.Component',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='connector.Component.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='connector.Component.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='connector.Component.id', index=2,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='connector.Component.attribute', index=3,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub_component', full_name='connector.Component.sub_component', index=4,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMPONENT_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=323,
)


_ATTRIBUTE = _descriptor.Descriptor(
  name='Attribute',
  full_name='connector.Attribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='connector.Attribute.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='connector.Attribute.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='connector.Attribute.id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=395,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='connector.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='svalue', full_name='connector.Value.svalue', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ivalue', full_name='connector.Value.ivalue', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dvalue', full_name='connector.Value.dvalue', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avalue', full_name='connector.Value.avalue', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=486,
)

_DESCRIPTION.fields_by_name['component'].message_type = _COMPONENT
_COMPONENT.fields_by_name['type'].enum_type = _COMPONENT_TYPE
_COMPONENT.fields_by_name['attribute'].message_type = _ATTRIBUTE
_COMPONENT.fields_by_name['sub_component'].message_type = _COMPONENT
_COMPONENT_TYPE.containing_type = _COMPONENT
_ATTRIBUTE.fields_by_name['value'].message_type = _VALUE
_VALUE.fields_by_name['avalue'].message_type = _VALUE
DESCRIPTOR.message_types_by_name['Description'] = _DESCRIPTION
DESCRIPTOR.message_types_by_name['Component'] = _COMPONENT
DESCRIPTOR.message_types_by_name['Attribute'] = _ATTRIBUTE
DESCRIPTOR.message_types_by_name['Value'] = _VALUE

Description = _reflection.GeneratedProtocolMessageType('Description', (_message.Message,), dict(
  DESCRIPTOR = _DESCRIPTION,
  __module__ = 'module_descriptor_pb2'
  # @@protoc_insertion_point(class_scope:connector.Description)
  ))
_sym_db.RegisterMessage(Description)

Component = _reflection.GeneratedProtocolMessageType('Component', (_message.Message,), dict(
  DESCRIPTOR = _COMPONENT,
  __module__ = 'module_descriptor_pb2'
  # @@protoc_insertion_point(class_scope:connector.Component)
  ))
_sym_db.RegisterMessage(Component)

Attribute = _reflection.GeneratedProtocolMessageType('Attribute', (_message.Message,), dict(
  DESCRIPTOR = _ATTRIBUTE,
  __module__ = 'module_descriptor_pb2'
  # @@protoc_insertion_point(class_scope:connector.Attribute)
  ))
_sym_db.RegisterMessage(Attribute)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), dict(
  DESCRIPTOR = _VALUE,
  __module__ = 'module_descriptor_pb2'
  # @@protoc_insertion_point(class_scope:connector.Value)
  ))
_sym_db.RegisterMessage(Value)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031jp.gaje.analog3.connector'))
# @@protoc_insertion_point(module_scope)
