/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.3 at Sun Oct  8 07:02:23 2017. */

#include "nano_compact_descriptor.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t compact_descriptor_Description_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, compact_descriptor_Description, component, component, &compact_descriptor_Component_fields),
    PB_LAST_FIELD
};

const pb_field_t compact_descriptor_Component_fields[6] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, compact_descriptor_Component, name, name, 0),
    PB_FIELD(  2, ENUM    , REQUIRED, STATIC  , OTHER, compact_descriptor_Component, type, name, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, compact_descriptor_Component, id, type, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, CALLBACK, OTHER, compact_descriptor_Component, attribute, id, &compact_descriptor_Attribute_fields),
    PB_FIELD(  5, MESSAGE , REPEATED, CALLBACK, OTHER, compact_descriptor_Component, sub_component, attribute, &compact_descriptor_Component_fields),
    PB_LAST_FIELD
};

const pb_field_t compact_descriptor_Attribute_fields[5] = {
    PB_FIELD(  1, ENUM    , REQUIRED, STATIC  , FIRST, compact_descriptor_Attribute, type, type, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, compact_descriptor_Attribute, ivalue, type, 0),
    PB_FIELD(  3, STRING  , REPEATED, CALLBACK, OTHER, compact_descriptor_Attribute, svalue, ivalue, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, compact_descriptor_Attribute, id, svalue, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(compact_descriptor_Description, component) < 65536 && pb_membersize(compact_descriptor_Component, attribute) < 65536 && pb_membersize(compact_descriptor_Component, sub_component) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_compact_descriptor_Description_compact_descriptor_Component_compact_descriptor_Attribute)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(compact_descriptor_Description, component) < 256 && pb_membersize(compact_descriptor_Component, attribute) < 256 && pb_membersize(compact_descriptor_Component, sub_component) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_compact_descriptor_Description_compact_descriptor_Component_compact_descriptor_Attribute)
#endif


